meta:                                       
    site_title: "Gao Lei's Blog"
    site_subtitle: "渐行渐远"
    site_content: "博客,IT技术,锻炼，朋友，学习那点事"
    site_language: "CN"

    defualt_limit: 50
    author:
        full_name: Gao Lei
        short_name: Leizi
        name: 
        email: gaolei786@gmail.com


baseurl: http://reserverisk.github.com
markdown: kramdown
pygments: true
permalink: /:year/:month/:day/:title
auto: true
debug: true

links:
    - url: "http://cos.name"
      name: 统计之都
      title: 关注统计
    - url: "http://cos.name.cn"
      name: 统计之都论坛
      title: 三人行必有我师也


